name: Build

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build xcode project
        uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          project: Ejectify.xcodeproj
          scheme: Ejectify
          destination: platform=macOS
          action: build